### ISSUE TITLE
Adding a rough README

### ISSUE THREAD

**Issue by jakirkham** [regro/conda-press#1]
Would be great to have a README outlining the following.

1. What we are solving (overview)
2. How to install
    1. For end users
    2. For developers
3. More technical details about what we are doing
4. How to get involved

This is just my rough sketch of what this might look like. Please feel free to add, remove, reorganize, clarify this list as make sense. 🙂

**Comment by scopatz** [comment]
initial readme added!

**Comment by jakirkham** [comment]
Thanks Anthony!
