### ISSUE TITLE
[Question] How does conda-press handle relocation

### ISSUE THREAD

**Issue by SylvainCorlay** [regro/conda-press#22]
It does not seem that python wheels have means to relocate binary files like conda does. Conda also replaces the prefix in text files upon installation.

What is conda-press' approach to that problem?

**Comment by SylvainCorlay** [comment]
Since we don't where the wheel can be installed, a good thing to do may be for conda-press to completely remove the placeholder prefix in binary and text files. This would handle the case the install prefix is a standard path?

**Comment by SylvainCorlay** [comment]
It may be a good improvement for python wheels to get conda-style relocation features...

Cc @ncoghlan

**Comment by SylvainCorlay** [comment]
> I am open to options here. If you had a specific file / package / use case it would make it easier to talk about concrete solutions.

Yes! We would like to package xeus-python as a wheel. It is a new Python kernel for Jupyter that supports the debug adapter protocol and we are building the jupyterlab frontend.

xeus-python requires binary relocation to be functional.

**Comment by ncoghlan** [comment]
At the binary level, `pip`/`wheel`/etc rely on the C/C++ artifacts themselves being built to be relocatable (using `$ORIGIN` in `RPATH`, that kind of thing). They don't support post-install fix-ups the way they do for shebang lines.

**Comment by SylvainCorlay** [comment]
> They don't support post-install fix-ups the way they do for shebang lines.

OK, that is what I thought.

(Conda does a lot of that, especially for things that require full paths. For example, kernel specs are typically relocated to include the installation prefix. The same goes as soon as a full path including the prefix is present in a binary file...)

Hence my question for conda-press: how does it deal with files in conda packages that contain the conda placeholder for the prefix string?

**Comment by scopatz** [comment]
Some fixes in #32

**Comment by SylvainCorlay** [comment]
I am closing this one as we figured a way for xeus-python to not require prefix replacement in binary files.

**Comment by scopatz** [comment]
Great!
