### ISSUE TITLE
Refactoring to use a config parameter pattern

### ISSUE THREAD

**Issue by marcelotrevisani** [regro/conda-press#35]
It would be good to refactor the code to use a config parameter pattern (or maybe data class) instead of passing a lot of arguments as keywords to functions. it is interesting because it will simplify the code and we can do some processing before exposing the parameter if we want to.

**Comment by marcelotrevisani** [comment]
What do you thinkg @scopatz  ?

**Comment by scopatz** [comment]
Yeah, I think this is a good idea.  We are getting a lot of config parameters. It would be better to pass around one object.  (Maybe a dataclass even!)

**Comment by scopatz** [comment]
True, do we need this to work on Python 3.6, though?

**Comment by marcelotrevisani** [comment]
> True, do we need this to work on Python 3.6, though?

I think we do not **need** it for Python 3.6. Should we go ahead and do this refactoring using ``dataclass``?

**Comment by scopatz** [comment]
Yeah, I think so :wink:

**Comment by marcelotrevisani** [comment]
By the way, I just saw that there is a project called ``dataclasses`` which backport ``dataclass`` to Python 3.6

**Comment by scopatz** [comment]
Awesome! Thanks so much @marcelotrevisani!
