### ISSUE TITLE
Add ``--config`` option

### ISSUE THREAD

**Issue by marcelotrevisani** [regro/conda-press#36]
It would be interesting to pass a ``yaml`` file to the ``conda-press`` and it will configure it automatically (using the same options when we using the command line).

That might be interesting to be implemented after we refactor the code to use the object parameter pattern. (#35)

cc: @scopatz

**Comment by scopatz** [comment]
Yep, I like this a lot

**Comment by marcelotrevisani** [comment]
Closing in favor of #42
