### ISSUE TITLE
ModuleNotFoundError: No module named 'conda'

### ISSUE THREAD

**Issue by tomkooij** [regro/conda-press#4]
I've installed conda-press on two different (Linux) systems (conda env with python 3.7, pip installed `xonsh`, `ruamel.yaml` and `lazyasd`). On both systems I cannot run `conda press` because it cannot `import conda.api`. Probably something to do with premissions in my conda envs. **Or is there a package that provides conda.api**? `pip install conda` breaks my conda install :-( 

Linux:
```
[tests (master)]: python test_condatools.py
Traceback (most recent call last):
  File "test_condatools.py", line 10, in <module>
    from conda_press.condatools import SYSTEM, SO_EXT
  File "/home/tom/conda-press/conda_press/condatools.xsh", line 18, in <module>
    from conda.api import SubdirData
ModuleNotFoundError: No module named 'conda'
```

Windows:
```
(conda_press) D:\github\conda-press\tests>python test_condatools.py
Traceback (most recent call last):
  File "test_condatools.py", line 10, in <module>
    from conda_press.condatools import SYSTEM, SO_EXT
  File "d:\Miniconda3\envs\conda_press\lib\site-packages\conda_press\condatools.xsh", line 18, in <module>
    from conda.api import SubdirData
ModuleNotFoundError: No module named 'conda'
```

**Comment by scopatz** [comment]
Recent versions of conda provide `conda.api`.  What version are you on?

**Comment by tomkooij** [comment]
I was using `conda 4.3.31`. I'll upgrade and report back.

**Comment by tomkooij** [comment]
Nope :-( I upgraded to the latest `conda` but still no luck importing `conda.api`:

```
(conda_press) D:\github\conda-press\tests>python test_condatools.py
Traceback (most recent call last):
  File "test_condatools.py", line 10, in <module>
    from conda_press.condatools import SYSTEM, SO_EXT
  File "d:\Miniconda3\envs\conda_press\lib\site-packages\conda_press\condatools.xsh", line 18, in <module>
    from conda.api import SubdirData
ModuleNotFoundError: No module named 'conda'

(conda_press) D:\github\conda-press\tests>conda --version
conda 4.6.14
```

**Comment by tomkooij** [comment]
Finally figured it out: From `conda 4.4` it  **is** possible to install conda in a virtual env.

It finally works :-) I'll see if I can create a PR with installation docs. (`requirements.txt` / `environment.yml`)

**Comment by scopatz** [comment]
Thanks!
