### ISSUE TITLE
[Question] Windows Platform: how does conda-press handle the two prefixes

### ISSUE THREAD

**Issue by SylvainCorlay** [regro/conda-press#56]
Binary packages install assets in both `PREFIX` and `LIBRARY_PREFIX`.

How does conda-press handle these two prefixes in wheels?

**Comment by scopatz** [comment]
Do you have an example? `xeus-python`? I am not sure what happens exactly

**Comment by SylvainCorlay** [comment]
Yes! We want to conda-press xeus-python soon, and publish a wheel! The latest release should not require any binary prefix replacement so it should be simpler now.
 
(xeus-python is currently the only kernel that implements the debugging protocol for https://github.com/jupyterlab/debugger).

**Comment by scopatz** [comment]
Is there a specific issue you are seeing with xeus-python v0.6.7?

**Comment by scopatz** [comment]
> We want to conda-press xeus-python soon, and publish a wheel!

Also, great!

**Comment by SylvainCorlay** [comment]
> Is there a specific issue you are seeing with xeus-python v0.6.7?

well, in general, I am seeing the `LIBRARY_PREFIX` as a directory at the root of the wheel archive

<img width="533" alt="Capture" src="https://user-images.githubusercontent.com/2397974/69530335-220a2500-0f72-11ea-9ef5-ae4e22b14ce4.PNG">

**Comment by scopatz** [comment]
I am not familiar enough with windows to understand if/what the issue is.  Does pip fail to install the whl that is generated?

**Comment by SylvainCorlay** [comment]
> I am not familiar enough with windows to understand if/what the issue is. Does pip fail to install the whl that is generated?

It will not fail to install the wheel, but the executables will be in `PREFIX/Library/bin` and not in the path...

**Comment by SylvainCorlay** [comment]
From conversations on gitter, this is more of a conda-forge (or even default channel issue) that conda-press probably cannot resolve.

Essentially, there should have been only one prefix on windws but this ship has sailed long ago and changing it now is not really possible.

**Comment by SylvainCorlay** [comment]
Closing as I don't think this is in scope for conda-press.
